Add prayer times for Qasre
kosratdev/muslim-data-ios pull request #14
Opened 2024-02-17 09:06 UTC by Muhammadbarznji

**Description:**
This pull request introduces essential updates to incorporate Qasre prayer time information into the database, along with the necessary city mapping. Additionally, relevant tests have been modified or added to ensure the accurate functioning of the system with the newly integrated data.

**Changes Made:**

**Database Update:**
- Qasre prayer time data has been added to the existing database schema. This includes fields for Fajr, Dhuhr, Asr, Maghrib, and Isha prayer times specific to Qasre.

**City Mapping:**
- The necessary city mapping has been implemented to link Qasre with its corresponding geographical coordinates. This ensures precise calculation of prayer times for the specified location.

**Test Updates:**
- Existing tests related to prayer time calculations have been updated to accommodate the inclusion of Qasre. New test cases have been added to verify the accuracy of the data integration and mapping processes.
- New tests for city mapping have been added to ensure that the system correctly associates Qasre with its geographical coordinates.

2024-02-17 19:18 UTC, kosratdev requested changes
Thank you very much for your efforts kaka @Muhammadbarznji. Please just update the database version and I will add the MD file to the Assets folder to keep track the DB changes.

2024-02-17 19:18 UTC, kosratdev commented on MuslimData/Assets/muslim_db_v1.3.2.db
With every change in the database, I prefer to change the DB version (minor or patch). Furthermore, I'm considering creating an MD file in this folder to keep tracking db changes.

2024-02-18 16:29 UTC, Muhammadbarznji commented on MuslimData/Assets/muslim_db_v1.3.2.db
Hi kak @kosratdev, Thanks for your comments! I've addressed the changes you mentioned in the PR. The database version has been successfully updated,

2024-02-18 17:37 UTC, kosratdev approved these changes
Looks good for me. Thank you very much for your efforts 👏

2024-02-18 17:37 UTC, merged