Support swift package
kosratdev/muslim-data-ios pull request #25
Opened 2024-03-24 19:54 UTC by kosratdev

2024-03-29 08:52 UTC, Muhammadbarznji commented on MuslimData.podspec
The way I see it we need to add a deployment target here.
https://guides.cocoapods.org/syntax/podspec.html#deployment_target

2024-03-30 08:18 UTC, Muhammadbarznji commented on Example/MuslimDataExample/Azkars/AzkarChapters/AzkarChaptersScreen.swift
> +        NavigationSplitView {
Why used NavigationSplitView instead of NavigationStack?

2024-03-30 10:06 UTC, kosratdev commented on MuslimData.podspec
Done. Check it again.

2024-03-30 10:46 UTC, Muhammadbarznji requested changes

2024-03-30 10:46 UTC, Muhammadbarznji commented on Sources/MuslimData/Extensions/DateExtensions.swift
>      /// Format date to "MM-dd" pattern which will be used to get prayers fro this date in the prayer database.
Format the date to "MM-dd" pattern which will be used to get prayers from this date in the prayer database.

2024-03-30 10:46 UTC, Muhammadbarznji commented on Sources/MuslimData/Extensions/SequenceExtensions.swift
> +//  File.swift
Rename: File -> SequenceExtensions

2024-03-30 12:17 UTC, kosratdev commented on Example/MuslimDataExample/Azkars/AzkarItems/AzkarItemsScreen.swift
> +    var chapterId: Int
Done.

2024-03-30 12:20 UTC, kosratdev commented on Example/MuslimDataExample/PrayerTimes/PrayerScreen.swift
> +    var location: Location {
For easier access to variables, for example, instead of using this `prayerViewModel.location.countryCode` we shorten it to `location.countryCode`. If you prefer I can remove it.

2024-03-30 12:23 UTC, kosratdev commented on Sources/MuslimData/Extensions/DateExtensions.swift
>      /// Format date to "MM-dd" pattern which will be used to get prayers fro this date in the prayer database.
Done

2024-03-30 12:24 UTC, kosratdev commented on Sources/MuslimData/Extensions/SequenceExtensions.swift
> +//  File.swift
Done

2024-03-31 05:43 UTC, Muhammadbarznji commented on Example/MuslimDataExample/PrayerTimes/PrayerScreen.swift
> +    var location: Location {
No, it is good.

2024-03-31 05:45 UTC, Muhammadbarznji approved these changes
LGTM! Thanks.

2024-03-31 10:50 UTC, merged